### PR TITLE
Fixed deprecations

### PR DESCRIPTION
**Pull request by antonpaisov**
Atom has api freeze since version 0.174
Fixed deprecation warnings according to the API

### CODE REVIEW

**Comment by tombell** [comment]
Pushed out an updated release for this for people.

**Comment by antonpaisov** [comment]
Cool! Thanks!

**Comment by antonpaisov** [comment]
it looks like there're few other things to fix there for Shadow DOM compatibility, I'll try to fix it asap.
wasn't getting those errors before ^^

**Comment by tombell** [comment]
Cool, just open a PR, and I'll get it shipped.

**Comment by antonpaisov** [comment]
ok! but it appears that this PR isn't working in a correct way.
Maybe you should roll it back (push 0.27.1 version with rollback for now) and I'll let you know, when I'll fix it?
Sorry about this mess

**Pull request merged**
